name: CI

on:
  workflow_dispatch: {}
  push:
    tags:
      - '*'
    branches:
      - 'ci'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push-cnab:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/container-package-app:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push CNAB
        run: |
          az login --service-principal --username ${{ secrets.AZURE_PRINCIPAL_NAME }} --tenant ${{ secrets.AZURE_TENANT_ID }}  --password ${{ secrets.AZURE_CERTIFICATE }}
          az acr login --name tdkk8soffer
          cpa verify
          cpa buildbundle
