name: CI

on:
  workflow_dispatch: {}
  push:
    tags:
      - '*'
    branches:
      - 'ci'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push-cnab:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/container-package-app:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push CNAB
        run: |
          docker login tdkk8soffer.azurecr.io --username ${{ secrets.AZURE_ACR_USERNAME }} --password ${{ secrets.AZURE_ACR_PASSWORD }}
          cpa verify
          cpa buildbundle
